baseURL: ""
languageCode: en-us
theme: PaperMod
title: Redwan Benmansour

defaultContentLanguage: fr
defaultContentLanguageInSubdir: true


params:
  displayFullLangName: true
  defaultTheme: light
  disableThemeToggle: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowDate: true
  author: Redwan Benmansour
  
  

languages:
  en:
    languageName: ğŸ‡¬ğŸ‡§
    weight: 10
    contentDir: content/en
    title: Redwan
    menu:
      main:
        - identifier: accueil
          name: ğŸ  Home 
          url: /en/
          weight: 10
        - identifier: about
          name: ğŸ™‚ About
          url: /en/about/
          weight: 20
        - identifier: projets
          name: ğŸ”§ Projects
          url: /en/projects/
          weight: 30
    params:
      profileMode:
        enabled: true
        title: "Redwan Benmansour" # optional default will be site title
        subtitle: "Second-year student in EEE, I am passionate about my projects and aim to become an engineer. I am eager to master modern technology to create innovative solutions for a better future."
        imageUrl: "en/IMG_1576.jpg" # optional
        imageTitle: "Redwan Benmansour" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: Download resume
            url: "/en/CV.pdf"
      DateFormat: "January 2, 2006"
      socialIcons: # optional
        - name: "linkedin"
          url: "https://www.linkedin.com/in/redwan-benmansour-48502117a/"
        - name: "github"
          url: "https://github.com/redwanbnmnsr"
        - name: "email"
          url: "mailto:redwan.benmansour@outlook.com"

  fr:
    languageName: ğŸ‡«ğŸ‡·
    weight: 20
    title: Redwan
    contentDir: content/fr
    menu:
      main:
        - identifier: accueil
          name: ğŸ  Accueil 
          url: /fr/
          weight: 10
        - identifier: about
          name: ğŸ™‚ Ã€ propos
          url: /fr/about/
          weight: 20
        - identifier: projects
          name: ğŸ”§ Projets
          url: /fr/projects/
          weight: 30


    params:
      profileMode:
        enabled: true
        title: "Redwan Benmansour" # optional default will be site title
        subtitle: "Ã‰tudiant en deuxiÃ¨me annÃ©e de GEII. Je suis passionnÃ© par mes projets et je souhaite devenir ingÃ©nieur. J'ai hÃ¢te de maÃ®triser les technologies modernes afin de crÃ©er des solutions innovantes pour un avenir meilleur."
        imageUrl: "fr/IMG_1576.jpg" # optional
        imageTitle: "Redwan Benmansour" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: TÃ©lÃ©charger le CV
            url: "/fr/CV.pdf"
      DateFormat: "2 January 2006"

      socialIcons: # optional
        - name: "linkedin"
          url: "https://www.linkedin.com/in/redwan-benmansour-48502117a/"
        - name: "github"
          url: "https://github.com/redwanbnmnsr"
        - name: "email"
          url: "mailto:redwan.benmansour@outlook.com"
