baseURL: ""
languageCode: en-us
theme: PaperMod
title: Redwan Benmansour


defaultContentLanguage: fr
defaultContentLanguageInSubdir: true


params:
  displayFullLangName: true
  mainSections:
  - projects
  defaultTheme: light
  disableThemeToggle: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowDate: true
  author: Redwan Benmansour
  images: ["IMG_1576.jpg"]


languages:
  en:
    languageName: ğŸ‡¬ğŸ‡§
    weight: 10
    contentDir: content/en
    title: Redwan
    menu:
      main:
        - identifier: accueil
          name: ğŸ  Home 
          url: /en/
          weight: 10
        - identifier: about
          name: ğŸ™‚ About
          url: /en/about/
          weight: 20
        - identifier: projets
          name: ğŸ”§ Projects
          url: /en/projects/
          weight: 30
    params:
      images: ["IMG_1576.jpg"]
      profileMode:
        enabled: true
        title: "Redwan Benmansour" # optional default will be site title
        subtitle: "Third-year student in EEE, I'm looking for an engineering school in the fields of electrical energy or IoT."
        imageUrl: "IMG_1576.jpg" # optional
        imageTitle: "Redwan Benmansour" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: Download resume
            url: "/en/CV_EN_Redwan_BENMANSOUR.pdf"
      DateFormat: "January 2, 2006"
      socialIcons: # optional
        - name: "linkedin"
          url: "https://www.linkedin.com/in/redwan-benmansour-48502117a/"
        - name: "github"
          url: "https://github.com/redwanbnmnsr"
        - name: "email"
          url: "mailto:redwan.benmansour@outlook.com"

  fr:
    languageName: ğŸ‡«ğŸ‡·
    weight: 20
    title: Redwan
    contentDir: content/fr
    menu:
      main:
        - identifier: accueil
          name: ğŸ  Accueil 
          url: /fr/
          weight: 10
        - identifier: about
          name: ğŸ™‚ Ã€ propos
          url: /fr/about/
          weight: 20
        - identifier: projects
          name: ğŸ”§ Projets
          url: /fr/projects/
          weight: 30


    params:
      images: ["IMG_1576.jpg"]
      profileMode:
        enabled: true
        title: "Redwan Benmansour" # optional default will be site title
        subtitle: "Ã‰tudiant en troisÃ¨me annÃ©e de BUT GEII, je suis Ã  la recherche d'une Ã©cole d'ingÃ©nieur dans les domaines de l'Ã©nergie Ã©lectrique ou de l'IoT. "
        imageUrl: "IMG_1576.jpg" # optional
        imageTitle: "Redwan Benmansour" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: TÃ©lÃ©charger le CV
            url: "/fr/CV_FR_Redwan_BENMANSOUR.pdf"
      DateFormat: "2 January 2006"


      socialIcons: # optional
        - name: "linkedin"
          url: "https://www.linkedin.com/in/redwan-benmansour/"
        - name: "github"
          url: "https://github.com/redwanbnmnsr"
        - name: "email"
          url: "mailto:redwan.benmansour@outlook.com"
